### ISSUE TITLE
How to read files in this kind of type?

### ISSUE THREAD

**Issue by RooneyLong** [malywut/devappsgpt#1]
Hello! It is surprising to find open resources related to this book.
I wonder how to read files in this kind of type? Is there any way to switch them into .pdf files?
Thank you and look forward to your reply!

**Comment by malywut** [comment]
Hi sorry I didn't see  your message because this project is only the code for the static website for the book  - it generates appswithgpt.com
This repository has no use. The code examples are visible on https://github.com/malywut/gpt_examples
